image: Visual Studio 2017 RC
version: '0.1.0.{build}'
configuration:
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_build:
- nuget install Cake -ExcludeVersion
build_script:
- .\Cake\Cake.exe --target=Build
after_build:
- .\Cake\Cake.exe --target=Pack
test_script:
- .\Cake\Cake.exe --target=UnitTest
artifacts:
- path: out\*
